apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole-server
  namespace: argocd
spec:
  replicas: 5
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
  project: default
  source:
    chart: pihole
    repoURL: https://mojo2600.github.io/pihole-kubernetes/
    targetRevision: 2.9.1
    helm:
      releaseName: pihole-server
      values: |
        adlists:
          - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
        ingress:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: adblocker
  syncPolicy:
      syncOptions:
      - CreateNamespace=true
