apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: pihole-rollout
spec:
  replicas: 5
  analysis:
    successfulRunHistoryLimit: 10
    unsuccessfulRunHistoryLimit: 10
  selector:
    matchLabels:
      app: pihole-server
  template:
    metadata:
      labels:
        app: pihole-server
        release: pihole-server
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
