apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: pihole-rollout
spec:
  replicas: 5
  analysis:
    successfulRunHistoryLimit: 10
    unsuccessfulRunHistoryLimit: 10
  selector:
    matchLabels:
      name: pihole-server
